// PIXI.js Engine

import * as PIXI from "pixi.js";
import "@pixi/unsafe-eval";

import { makeAutoObservable } from "mobx";
import { Store, RootStore } from "../store";
import { EngineEntity } from "./entity";
import { FrameModule } from "./test";

export class EngineStore implements Store {
    Frame!: FrameModule;

    rootStore: RootStore;
    ticker: PIXI.Ticker | undefined;
    stage: PIXI.Container | undefined;
    app: PIXI.Application | undefined;
    entities: { [key: string]: EngineEntity } = {};

    disposers: { [key: string]: Function[] } = {};
    renderFunctions: { [key: string]: Function } = {};
    displayObjects: { [key: string]: PIXI.DisplayObject } = {};

    constructor(rootStore: RootStore) {
        makeAutoObservable(this, {
            disposers: false,
            renderFunctions: false,
            displayObjects: false,
            rootStore: false,
            Frame: false,
            loadModules: false,
        });
        this.rootStore = rootStore;
    }

    loadModules() {
        this.Frame = new FrameModule(this.rootStore);
    }

    start(parent: HTMLElement) {
        this.app = this.createApp(parent);
        this.stage = this.app.stage;
        this.ticker = this.app.ticker;
        // displayObject.zIndex = -1000;
        // Engine.stage.sortableChildren = true;
    }

    createApp(parent: HTMLElement) {
        const app = new PIXI.Application({
            background: "#000000",
            resizeTo: window,
        });
        parent.appendChild(app.view as HTMLCanvasElement);
        return app;
    }

    add(entity: EngineEntity) {
        this.entities[entity.id] = entity;
        // very important to pass the proxy generated by mobX, not ~entity~
        const disposers = this.renderEntity(this.entities[entity.id]);
        this.disposers[entity.id] = disposers;
        return this.entities[entity.id];
    }

    remove(entity: EngineEntity) {
        delete this.entities[entity.id];
        for (let disposer of this.disposers[entity.id]) {
            disposer();
        }
    }

    private renderEntity(entity: EngineEntity): Function[] {
        return this.renderFunctions[entity.type](entity);
    }

    getDisplayObject(entityId: string) {
        return this.displayObjects[entityId];
    }

    addDisplayObject(entityId: string, displayObject: PIXI.DisplayObject) {
        this.displayObjects[entityId] = displayObject;
        this.stage?.addChild(displayObject);
    }

    removeDisplayObject(entityId: string) {
        if (this.displayObjects[entityId]) {
            this.stage?.removeChild(this.displayObjects[entityId]);
        }
    }
}
